# Generated by Django 4.2.11 on 2024-04-27 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="users",
            field=models.ManyToManyField(
                related_name="spaces", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="HomeLinkUser",
        ),
    ]
