# Generated by Django 4.2.11 on 2024-09-23 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_customuser_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
