# Generated by Django 4.2.11 on 2024-09-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_device_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandsLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triggers", models.JSONField()),
                ("ttl", models.DurationField(blank=True, null=True)),
                ("results", models.JSONField()),
            ],
        ),
    ]
