# Generated by Django 4.2.11 on 2024-10-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_commandslink"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandslink",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
