# Generated by Django 4.2.11 on 2024-08-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_alter_device_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="command",
            name="data",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="command",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="command",
            name="repeat_interval",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
