# Generated by Django 4.2.11 on 2024-10-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_commandslink_started_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="command",
            name="devices",
        ),
        migrations.AddField(
            model_name="command",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.device",
            ),
        ),
    ]
