# Generated by Django 4.2.11 on 2024-10-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_commandslink_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="command",
            name="self_execute",
            field=models.BooleanField(default=False),
        ),
    ]
